In [4]:
import numpy as np
import pandas as pd

In [5]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [12]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [17]:
movies = movies.merge(credits,on='title')

In [18]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [20]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [21]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [24]:
movies.dropna(inplace=True)

In [26]:
movies.duplicated().sum()

0

In [27]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [32]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [34]:
movies['genres'] = movies['genres'].apply(convert)

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [37]:
movies['keywords'] = movies['keywords'].apply(convert)

In [38]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [41]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [43]:
movies['cast'] = movies['cast'].apply(convert3)

In [44]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [45]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [47]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [49]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [50]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [52]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [57]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [58]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [66]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [67]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tag,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili...","[John, Carter, is, a, war-weary,, former, mili..."

In [68]:
new_df = movies[['movie_id','title','tags']]

In [71]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Ankit Limone\AppData\Local\Temp\ipykernel_19452\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [72]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [73]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [76]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Ankit Limone\AppData\Local\Temp\ipykernel_19452\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [77]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [97]:
import nltk

In [98]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [99]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [101]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Ankit Limone\AppData\Local\Temp\ipykernel_19452\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [79]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [80]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [102]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [103]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [104]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [105]:
cv.get_feature_names()

C:\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [106]:
from sklearn.metrics.pairwise import cosine_similarity

In [111]:
similarity = cosine_similarity(vectors)

In [124]:
sorted(list(enumerate(similarity[0])),reverse = True,key=lambda x:x[1])[1:499]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957),
 (582, 0.24511108480187255),
 (1204, 0.24455799402225925),
 (1194, 0.2367785320221084),
 (61, 0.23179316248638274),
 (778, 0.23174488732966075),
 (4048, 0.2278389747471728),
 (1920, 0.22528177844479153),
 (2786, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2333, 0.20443988269091456),
 (3608, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4192, 0.2029530274475215),
 (1444, 0.20277677641345318),
 (74, 0.20246457179963143),
 (1089, 0.2020475485519274),
 (3675, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2971, 0.19252140716412977),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1201, 0.19088542889273336),
 (305, 0.1900748713929803),
 (4, 0.18929940971212042),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3327, 0.1860807318911967),
 (1275, 0.18394180184548975),
 (1329, 0.18394180184548975),
 (2999, 0.1813690625275029),
 (3999, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1071, 0.17954621161490197),
 (220, 0.1777046633277277),
 (184, 0.177343107178349),
 (1321, 0.17699808135119718),
 (168, 0.17521916101261562),
 (2204, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (36, 0.17316974359835272),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3538, 0.1711905958155815),
 (3162, 0.17040572913692198),
 (1982, 0.16943474841747153),
 (661, 0.1675415633166782),
 (529, 0.16742770563222897),
 (1831, 0.16742770563222897),
 (91, 0.16692446522239718),
 (41, 0.16563698349810535),
 (67, 0.16452254913212452),
 (150, 0.16426202236672155),
 (1537, 0.16222142113076254),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2515, 0.15907119074394446),
 (1178, 0.15789473684210528),
 (4010, 0.15737789507292674),
 (2731, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1383, 0.152008377581442),
 (111, 0.15018785229652767),
 (1344, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (513, 0.14843120879858804),
 (2075, 0.14808721943977307),
 (7, 0.14673479641335554),
 (2760, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1297, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1396, 0.14421498760030763),
 (1479, 0.14421498760030763),
 (1355, 0.14350946197048198),
 (1938, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3354, 0.1433848336691011),
 (1056, 0.1419745572840903),
 (1273, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1488, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2496, 0.1411956236812263),
 (95, 0.1404878717372541),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3409, 0.1391037210186643),
 (1965, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1327, 0.13834289277321493),
 (3781, 0.13834289277321493),
 (72, 0.13710212427677043),
 (843, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2169, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3982, 0.13530201829834768),
 (1808, 0.13518451760896877),
 (4348, 0.13497638119975428),
 (1322, 0.13476498501489081),
 (158, 0.13369695534647594),
 (502, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1560, 0.13334518676566626),
 (1373, 0.1324532357065044),
 (2378, 0.1324532357065044),
 (2584, 0.1324532357065044),
 (4079, 0.13157894736842107),
 (2133, 0.13124359177794215),
 (1015, 0.12988108336653278),
 (2181, 0.12988108336653278),
 (3622, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1774, 0.12977713690461004),
 (2873, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (369, 0.12824729401064427),
 (1086, 0.12824729401064427),
 (2686, 0.12824729401064427),
 (4230, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2970, 0.12725695259515557),
 (937, 0.126673647984535),
 (1741, 0.12565617248750865),
 (2480, 0.12565617248750865),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2450, 0.12515654358043973),
 (3628, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1096, 0.12487810821089254),
 (1158, 0.12487810821089254),
 (2652, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (3376, 0.12262786789699316),
 (1878, 0.12262786789699315),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1299, 0.12227899701112963),
 (2331, 0.12166606584807191),
 (2674, 0.12166606584807191),
 (3083, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1004, 0.1204950466257556),
 (1274, 0.1204950466257556),
 (1658, 0.1204950466257556),
 (1002, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3235, 0.11959121830873498),
 (1047, 0.11846977555181847),
 (1833, 0.11846977555181847),
 (2060, 0.11846977555181847),
 (2741, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (1715, 0.11803342130469506),
 (3721, 0.11803342130469506),
 (1673, 0.11803342130469505),
 (2789, 0.11803342130469505),
 (4000, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (454, 0.11707322644771176),
 (1617, 0.11707322644771176),
 (2284, 0.11707322644771176),
 (28, 0.116543309349613),
 (122, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (2547, 0.11587244366483038),
 (1497, 0.11551284429847784),
 (3212, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1220, 0.11470786693528089),
 (236, 0.11470786693528087),
 (1301, 0.11470786693528087),
 (85, 0.11412706387705432),
 (432, 0.11357771260606365),
 (1418, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1616, 0.11295649894498103),
 (123, 0.1124803176664619),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3147, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1348, 0.11164843913471803),
 (1575, 0.11164843913471803),
 (2372, 0.11141412945539662),
 (1512, 0.11141412945539661),
 (3309, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1574, 0.11020775375559674),
 (3428, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1031, 0.10968169942141635),
 (1945, 0.10968169942141635),
 (2148, 0.10968169942141635),
 (3008, 0.10968169942141635),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1524, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (3093, 0.10838874619051501),
 (3630, 0.10838874619051501),
 (740, 0.108388746190515),
 (786, 0.10814761408717502),
 (3498, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1237, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1166, 0.10619884881071831),
 (1501, 0.10619884881071831),
 (1745, 0.10619884881071831),
 (2161, 0.10619884881071831),
 (2634, 0.10619884881071831),
 (4135, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1496, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (2072, 0.10526315789473685),
 (3340, 0.10526315789473685),
 (2498, 0.10471347707292387),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1195, 0.10390486669322622),
 (1771, 0.10390486669322622),
 (2817, 0.10390486669322622),
 (2439, 0.103851623099316),
 (654, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (624, 0.1037571695799112),
 (2323, 0.1037571695799112),
 (2456, 0.1037571695799112),
 (2521, 0.1037571695799112),
 (3055, 0.1037571695799112),
 (3621, 0.1037571695799112),
 (3839, 0.1037571695799112),
 (1455, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1082, 0.10259783520851541),
 (3152, 0.10259783520851541),
 (3634, 0.10259783520851541),
 (3755, 0.10259783520851541),
 (3874, 0.10259783520851541),
 (4097, 0.10259783520851541),
 (2106, 0.10218988991416095),
 (2762, 0.10147651372376076),
 (3663, 0.10147651372376076),
 (3954, 0.10147651372376076),
 (3441, 0.10138838820672659),
 (508, 0.101338918387628),
 (1294, 0.101338918387628),
 (2247, 0.10133891838762799),
 (1405, 0.10060545457319173),
 (1439, 0.10060545457319173),
 (2099, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (988, 0.10012523486435178),
 (1037, 0.10012523486435178),
 (1614, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1077, 0.09933992677987831),
 (1280, 0.09933992677987831),
 (1884, 0.09933992677987831),
 (2053, 0.09933992677987831),
 (4018, 0.09933992677987831),
 (4198, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3620, 0.0989541391990587),
 (3783, 0.0989541391990587),
 (3935, 0.0989541391990587),
 (1775, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1109, 0.0978231976089037),
 (1401, 0.0978231976089037),
 (1823, 0.0978231976089037),
 (2253, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1156, 0.09733285267845754),
 (1727, 0.09733285267845754),
 (1942, 0.09733285267845754),
 (2787, 0.09733285267845754),
 (4256, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2241, 0.09567297464698798),
 (2556, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (791, 0.09544271444636668),
 (1573, 0.09544271444636668),
 (2562, 0.09544271444636668),
 (4203, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (980, 0.09365858115816941),
 (1276, 0.09365858115816941),
 (1357, 0.09365858115816941),
 (1474, 0.09365858115816941),
 (1686, 0.09365858115816941),
 (1692, 0.09365858115816941),
 (1721, 0.09365858115816941),
 (2396, 0.09365858115816941),
 (2488, 0.09365858115816941),
 (2592, 0.09365858115816941),
 (2645, 0.09365858115816941),
 (2650, 0.09365858115816941),
 (2820, 0.09365858115816941),
 (3537, 0.09365858115816941),
 (3720, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (301, 0.09365858115816939),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1446, 0.09269795493186431),
 (1701, 0.09269795493186431),
 (3407, 0.09269795493186431),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (1756, 0.09197090092274487),
 (2093, 0.09197090092274487),
 (2651, 0.09197090092274487),
 (3736, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (239, 0.09125667909262308),
 (2570, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (997, 0.09086217008485092),
 (1233, 0.09086217008485092),
 (1846, 0.09086217008485092),
 (3881, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1306, 0.09037128496931669),
 (1480, 0.09037128496931669),
 (2251, 0.09037128496931669),
 (2957, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2363, 0.08998425413316952),
 (2796, 0.08998425413316952),
 (2856, 0.08998425413316952),
 (3389, 0.08998425413316952),
 (3443, 0.08998425413316952),
 (3462, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1906, 0.0891313035643173),
 (2115, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1027, 0.08885233166386385),
 (2660, 0.08885233166386385),
 (2868, 0.08885233166386385),
 (3322, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1783, 0.08830215713766959),
 (2109, 0.08830215713766959),
 (2713, 0.08830215713766959),
 (2740, 0.08830215713766959),
 (3553, 0.08830215713766959),
 (479, 0.08797691788472335),
 (752, 0.08749572785196143),
 (1832, 0.08749572785196143),
 (2448, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1249, 0.08740748201220976),
 (1259, 0.08740748201220976),
 (3448, 0.08740748201220976),
 (3449, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1530, 0.08671099695241201),
 (2880, 0.08671099695241201),
 (3556, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1378, 0.08603090020146065),
 (2583, 0.08603090020146065),
 (3135, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (1019, 0.08594700851870801),
 (2354, 0.08594700851870801),
 (32, 0.08520286456846099),
 (217, 0.08520286456846099),
 (142, 0.08471737420873576)]

In [132]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key=lambda x:x[1])[1:499]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [133]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.
Battle: Los Angeles
Predators
Small Soldiers
Jupiter Ascending
Meet Dave
U.F.O.
Lifeforce
Attack the Block
The Twilight Saga: Breaking Dawn - Part 2
The Host
The Fifth Element
Predator
Apollo 18
Ender's Game
Beowulf
Independence Daysaster
Krull
Edge of Tomorrow
Aliens in the Attic
Capricorn One
The Host
AVP: Alien vs. Predator
Star Trek Into Darkness
E.T. the Extra-Terrestrial
The Book of Life
Journey 2: The Mysterious Island
Escape from Planet Earth
Treasure Planet
John Carter
The Helix... Loaded
Guardians of the Galaxy
Battleship
Code 46
Impostor
The 5th Wave
Mad Max Beyond Thunderdome
Journey to Saturn
The Lovers
The Hitchhiker's Guide to the Galaxy
Prometheus
Home
The Thing
Final Fantasy: The Spirits Within
Lockout
Silent Running
Race to Witch Mountain
Transformers: Age of Extinction
Mission to Mars
Starship Troopers
Galaxina
Alien
Muppets from Space
Zathura: A Space Adventure
Tears of the Sun
Jimmy Neutron: Boy Genius
Independence Day: Resurgence
Green Lantern
Monsters vs Aliens
Men in Black II
Moonraker
Men in Black
Doom
Iron Man 3
Slither
The Last of the Mohicans
Silver Medalist
Under the Skin
Armageddon
AlienÂ³
Captain America: Civil War
Puss in Boots
Species
Transformers
The Inhabited Island
The Adventures of Pluto Nash
Transformers: Dark of the Moon
The Rock
Teenage Mutant Ninja Turtles III
Avengers: Age of Ultron
Earth to Echo
Mad Max: Fury Road
We Were Soldiers
Star Trek: Insurrection
Terminator Genisys
Serenity
The Time Machine
Underworld: Rise of the Lycans
The Astronaut's Wife
Gattaca
Sheena
Minority Report
Epic
Logan's Run
Galaxy Quest
Universal Soldier: The Return
A Sound of Thunder
The Darkest Hour
Nutty Professor II: The Klumps
Lost in Space
xXx
Highlander
Interstellar
Pirates of the Caribbean: On Stranger Tides
X-Men: Days of Future Past
Stargate: The Ark of Truth
Star Trek IV: The Voyage Home
Star Trek Beyond
Insurgent
Virgin Territory
Mirrormask
Suicide Squad
The Watch
Thunderbirds
The Covenant
Seven Samurai
Surrogates
The League of Extraordinary Gentlemen
Elektra
Herbie Fully Loaded
Close Range
Highlander: The Final Dimension
Godzilla 2000
Riddick
Star Trek
The Invasion
The Mortal Instruments: City of Bones
Thor: The Dark World
District 9
Star Trek: The Motion Picture
Megaforce
The Marine
Sleeper
Bill & Ted's Bogus Journey
Three Kings
Ladyhawke
Force 10 from Navarone
Mission: Impossible - Rogue Nation
Percy Jackson: Sea of Monsters
Martian Child
Fortress
Man of Steel
The Last Airbender
Lara Croft Tomb Raider: The Cradle of Life
Babylon A.D.
Jonah: A VeggieTales Movie
Repo Man
Red Planet
Flyboys
2001: A Space Odyssey
Hansel & Gretel: Witch Hunters
Ghosts of Mars
Arn: The Knight Templar
G.I. Joe: Retaliation
Planet 51
Damnation Alley
Moon
Timeline
Deep Rising
Spy Kids 3-D: Game Over
Silent Trigger
The Hunger Games: Mockingjay - Part 2
47 Ronin
The 13th Warrior
Split Second
Anacondas: The Hunt for the Blood Orchid
Something's Gotta Give
Jarhead
Superman III
My Big Fat Greek Wedding 2
Crocodile Dundee II
Bucky Larson: Born to Be a Star
Mission: Impossible III
Iron Man
Inkheart
Street Fighter: The Legend of Chun-Li
Pandorum
Dragonball Evolution
What Planet Are You From?
Sphere
Superman II
The Adjustment Bureau
Valley of the Wolves: Iraq
Journey to the Center of the Earth
Teenage Mutant Ninja Turtles II: The Secret of the Ooze
Hit & Run
Young Guns
Mad Max
Space Pirate Captain Harlock
Blackthorn
Supercross
Operation Chromite
Donovan's Reef
How to Train Your Dragon 2
Ant-Man
Planet of the Apes
The Day the Earth Stood Still
Mortal Kombat: Annihilation
Dances with Wolves
Jurassic World
X-Men Origins: Wolverine
The 6th Day
Dragon Blade
Dracula Untold
The Faculty
Doomsday
Star Wars: Clone Wars: Volume 1
Noah
Paul
Windtalkers
Red Cliff
Captain America: The Winter Soldier
Deep Impact
Predator 2
Prince of Persia: The Sands of Time
Hanna
The Matrix Revolutions
Hellboy II: The Golden Army
Anna and the King
The Thin Red Line
You Only Live Twice
Allegiant
Walking Tall
Dolphin Tale 2
Down to Earth
Dragonslayer
Source Code
The Blood of Heroes
Tomorrowland
Night at the Museum: Battle of the Smithsonian
The Wolverine
Saints and Soldiers
Clash of the Titans
Teenage Mutant Ninja Turtles
Oblivion
Maleficent
Looper
The Adventures of Huck Finn
Robin Hood
The Book of Eli
Solaris
BloodRayne
Risen
Dogma
Chicken Little
The Hunger Games: Mockingjay - Part 1
The Last Legion
This Means War
Dragon Wars: D-War
The Expendables 3
Spider-Man 3
Krrish
Sea Rex 3D: Journey to a Prehistoric World
Alien: Resurrection
The Monkey King 2
Beastmaster 2: Through the Portal of Time
Pink Narcissus
Star Wars: Episode III - Revenge of the Sith
Hook
I Am Number Four
Lara Croft: Tomb Raider
The Brothers Grimm
The Art of War
The World Is Not Enough
The Lord of the Rings: The Fellowship of the Ring
Scary Movie 4
Phenomenon
How to Lose Friends & Alienate People
The World's End
Blood and Chocolate
London
Mighty Joe Young
Soldier
Return of the Jedi
G-Force
The Tourist
Firefox
Diamonds Are Forever
Steel
Waterworld
The Chronicles of Riddick
300
The Nutty Professor
Spawn
The Newton Boys
The Golden Child
Superman IV: The Quest for Peace
Blade: Trinity
Alice Through the Looking Glass
Star Wars: Episode I - The Phantom Menace
Abraham Lincoln: Vampire Hunter
Star Trek III: The Search for Spock
Becoming Jane
Crouching Tiger, Hidden Dragon
MacGruber
The Forsaken
Harper
The Order
Superman Returns
Dune
It's a Mad, Mad, Mad, Mad World
Jekyll and Hyde ... Together Again
They Live
To Write Love on Her Arms
Gentleman's Agreement
Mortal Kombat
Letters from Iwo Jima
Area 51
Creature
Tracker
The Lost World: Jurassic Park
The Time Traveler's Wife
Passchendaele
In Time
The Four Feathers
Jackass 3D
Green Zone
The Lord of the Rings: The Two Towers
Space Cowboys
The Messenger: The Story of Joan of Arc
Star Trek: First Contact
The Running Man
Transformers: Revenge of the Fallen
Exodus: Gods and Kings
The Stepford Wives
Ice Age: Continental Drift
The Scorpion King
The Indian in the Cupboard
Delgo
Spice World
Megiddo: The Omega Code 2
Escape from the Planet of the Apes
Conquest of the Planet of the Apes
Hav Plenty
A.I. Artificial Intelligence
Pompeii
I, Robot
Just Go with It
Children of Men
Robin and Marian
The Barbarians
Warlock: The Armageddon
Spy Kids: All the Time in the World
Mirror Mirror
Battlefield Earth
First Knight
The Twilight Saga: New Moon
Rambo: First Blood Part II
Resident Evil
The Bodyguard
Princess Mononoke
X-Men: The Last Stand
Ghostbusters
Around the World in 80 Days
Flags of Our Fathers
Lucy
30 Minutes or Less
Tank Girl
In the Land of Blood and Honey
Fetching Cody
Special
Aqua Teen Hunger Force Colon Movie Film for Theaters
Batman v Superman: Dawn of Justice
Jurassic Park III
The Saint
The Core
A Scanner Darkly
Lawrence of Arabia
Monsters
Pixels
Goosebumps
Warm Bodies
The Princess Bride
The Lunchbox
Men in Black 3
Quantum of Solace
The Abyss
Proof of Life
Congo
The Iron Giant
Extreme Ops
Space Chimps
The Fountain
Savva. Heart of the Warrior
The Borrowers
Timecop
Red Sonja
My Stepmother is an Alien
Firestarter
District B13
Ong Bak 2
Star Trek II: The Wrath of Khan
Iris
Exiled
The Dead Undead
Mercy Streets
Cloud Atlas
Thor
Night at the Museum
Terminator 2: Judgment Day
Mars Attacks!
I Spy
Superman
Flight of the Intruder
Aladdin
Alpha and Omega: The Legend of the Saw Tooth Cave
Beyond Borders
Charlie's Angels: Full Throttle
San Andreas
X-Men
Star Trek VI: The Undiscovered Country
Close Encounters of the Third Kind
Centurion
Cargo
Star Wars: Episode II - Attack of the Clones
Resident Evil: Afterlife
Gravity
Love & Basketball
Terminator Salvation
Ballistic: Ecks vs. Sever
Gamer
The Shadow
The Lucky One
Dreaming of Joseph Lees
Pirates of the Caribbean: Dead Man's Chest
Big Hero 6
Sahara
Sherlock Holmes
Divergent
Star Trek: Generations
I Dreamed of Africa
The Brothers Bloom
Return to the Blue Lagoon
Seventh Son
The Legend of the Lone Ranger
Womb
Max Keeble's Big Move
March or Die
The Terminator
Duel in the Sun
Dr. No
Love Me Tender
Gladiator
The Adventures of Pinocchio
Me Before You
Eragon
Signs
Dick Tracy
Automata
House of Flying Daggers
Witless Protection
Captain America: The First Avenger
The Martian
Mystery Men
Paul Blart: Mall Cop
Holes
Caravans
Dude, Whereâ€™s My Car?
Grabbers
Walking With Dinosaurs
My Favorite Martian
Cloverfield
Southland Tales
The Golden Compass
Mars Needs Moms
The Three Musketeers
Miss Congeniality 2: Armed and Fabulous
Rambo III
The Adventures of Sharkboy and Lavagirl
Quest for Camelot
Ishtar
Grease
Platoon
Pan
Pirates of the Caribbean: The Curse of the Black Pearl
City of Angels
George and the Dragon
Two Lovers
Somewhere in Time
Benji
Love in the Time of Monsters
Spectre
Six Days Seven Nights
Supernova
Guess Who
Tuck Everlasting
Of Horses and Men
Gabriela
The Croods
Kate & Leopold
127 Hours
Alice in Wonderland
Ghost Rider
Flushed Away

In [131]:
new_df.iloc[1216].title

'Aliens vs Predator: Requiem'

In [134]:
import pickle

In [136]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [137]:
pickle.dump(similarity,open('similarity.pkl','wb'))